export const RETRIEVE_POSTS = 'RETRIEVE_POSTS';
export const ITEMS_HAS_ERRORED = 'ITEMS_HAS_ERRORED';
export const ITEMS_IS_LOADING = 'ITEMS_IS_LOADING';
export const REDIRECT_ON_SUCCESS = 'REDIRECT_ON_SUCCESS';
export const CREATE_POST = 'CREATE_POST';
export const UPDATE_POST = 'UPDATE_POST';
export const REMOVE_POST = 'REMOVE_POST';
export const IS_AUTHORIZED = 'IS_AUTHORIZED';